name: "Go Test"
description: "Run Go tests with race detection"

inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: ">=1.24"
  working-directory:
    description: "Working directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        CGO_ENABLED: 1
      run: go test -race -v ./...
